"""
PRD (Product Requirement Document) Generation Service for Milestone 3.
Leverages Google Gemini (gemini-3.6-flash) with Groq and heuristic fallback to generate
comprehensive, enterprise-grade PRDs grounded in authentic customer feedback.
"""

import os
import json
import uuid
import logging
from datetime import datetime, timezone
from typing import Dict, Any, List, Optional

from config import settings
from services.ai_service import get_gemini_client, get_groq_client, get_mistral_client, _extract_json_from_text, GEMINI_MODELS, GROQ_MODELS, MISTRAL_MODELS
from services.text_mining import (
    REQUEST_MARKERS,
    content_tokens,
    match_records_by_terms,
    rating_stats,
    request_phrases,
    titleize,
    top_phrases,
)
from services.theme_extraction import _resolve_category, _resolve_sentiment
import database
from database import db
import fallback_db

logger = logging.getLogger(__name__)


def _build_evidence_section(evidence: Optional[Dict[str, Any]]) -> str:
    """Render the provenance block: what this document was generated from and how."""
    if not evidence:
        return ""

    lines = [
        "## Evidence & Method",
        "| Item | Value |",
        "| :--- | :--- |",
        f"| Generated by | {evidence.get('generated_by') or 'n/a'} |",
        f"| Workspace | {evidence.get('workspace') or 'n/a'} |",
        f"| Records analysed | {evidence.get('records_analyzed')} |",
        f"| Records supporting this document | {evidence.get('records_supporting_this_document')} |",
        f"| Average rating of those records | {evidence.get('avg_rating') if evidence.get('avg_rating') is not None else 'not rated'} |",
        f"| Negative reports among them | {evidence.get('negative_reports')} |",
    ]
    if evidence.get("terms"):
        lines.append(f"| Phrases users wrote | {', '.join(str(term) for term in evidence['terms'])} |")
    if evidence.get("method"):
        lines.extend(["", f"*Method:* {evidence['method']}"])
    lines.append("")
    return "\n".join(lines)


def _build_markdown_from_prd(prd: Dict[str, Any]) -> str:
    """Format structured PRD data into clean, professional GitHub-flavored Markdown."""
    title = prd.get("title", "Product Requirement Document")
    status = prd.get("status", "draft").upper()
    version = prd.get("version", "1.0")
    created = prd.get("created_at", datetime.now(timezone.utc).strftime("%Y-%m-%d"))

    md = [
        f"# {title}",
        f"**Status:** `{status}` | **Version:** `{version}` | **Generated:** `{created}`",
        "",
        "---",
        "",
        "## 1. Executive Summary",
        prd.get("executive_summary", "No executive summary provided."),
        "",
        _build_evidence_section(prd.get("evidence")),
        "",
        "## 2. Problem Statement & Customer Evidence",
        prd.get("problem_statement", "No problem statement provided."),
        "",
        "## 3. Goals & Success Objectives",
    ]

    for g in prd.get("goals_and_objectives", []):
        md.append(f"- {g}")
    md.append("")

    # Personas
    md.append("## 4. Target User Personas")
    for p in prd.get("target_users_and_personas", []):
        md.append(f"### Persona: {p.get('role', 'User')}")
        if p.get("description"):
            md.append(f"*{p.get('description')}*")
        if p.get("pain_points"):
            md.append("**Frictions:**")
            for pp in p.get("pain_points", []):
                md.append(f"  - {pp}")
        if p.get("goals"):
            md.append("**Goals:**")
            for gl in p.get("goals", []):
                md.append(f"  - {gl}")
        md.append("")

    # Scope
    md.append("## 5. Scope Definition")
    md.append("### In-Scope (MVP & Fast Follow)")
    for item in prd.get("scope_in", []):
        md.append(f"- {item}")
    md.append("")
    md.append("### Out-of-Scope (Future Iterations)")
    for item in prd.get("scope_out", []):
        md.append(f"- {item}")
    md.append("")

    # User Journeys
    if prd.get("user_journeys"):
        md.append("## 6. Key User Journeys")
        for uj in prd.get("user_journeys", []):
            md.append(f"**Step {uj.get('step', 1)} [{uj.get('stage', 'Action')}]:** {uj.get('user_action', '')}")
            md.append(f"> **System Behavior:** {uj.get('system_response', '')}")
            md.append("")

    # Functional Requirements
    md.append("## 7. Functional Requirements")
    for fr in prd.get("functional_requirements", []):
        pri = fr.get("priority", "P1")
        md.append(f"### [{fr.get('id', 'FR')}] {fr.get('title', 'Requirement')} `[{pri}]`")
        md.append(fr.get("description", ""))
        if fr.get("acceptance_criteria"):
            md.append("\n**Acceptance Criteria:**")
            for ac in fr.get("acceptance_criteria", []):
                md.append(f"- [ ] {ac}")
        if fr.get("edge_cases"):
            md.append("\n**Edge Cases:**")
            for ec in fr.get("edge_cases", []):
                md.append(f"- 🔍 {ec}")
        md.append("")

    # Non-Functional Requirements
    md.append("## 8. Non-Functional Requirements (NFRs)")
    md.append("*Proposed engineering targets — the feedback evidence does not measure infrastructure.*")
    for nfr in prd.get("non_functional_requirements", []):
        cat = nfr.get("category", "General")
        md.append(f"- **{cat}:** {nfr.get('requirement', '')}")
    md.append("")

    # Success Metrics
    md.append("## 9. Success Metrics & Key Performance Indicators")
    md.append("*Baselines are measured from this workspace's feedback; targets are proposals.*")
    md.append("| Metric | Baseline | Target | Tracking Mechanism |")
    md.append("| :--- | :--- | :--- | :--- |")
    for m in prd.get("success_metrics_kpis", []):
        md.append(f"| {m.get('metric', '')} | {m.get('baseline', 'N/A')} | {m.get('target', '')} | {m.get('tracking_mechanism', 'Telemetry')} |")
    md.append("")

    # Technical Architecture & Dependencies
    if prd.get("technical_dependencies"):
        md.append("## 10. Technical Architecture & Dependencies")
        for td in prd.get("technical_dependencies", []):
            md.append(f"- {td}")
        md.append("")

    # Risks & Mitigations
    if prd.get("risks_and_mitigations"):
        md.append("## 11. Risks & Mitigation Strategies")
        for rm in prd.get("risks_and_mitigations", []):
            sev = rm.get("severity", "medium").upper()
            md.append(f"- **Risk [{sev}]:** {rm.get('risk', '')}")
            md.append(f"  *Mitigation:* {rm.get('mitigation', '')}")
        md.append("")

    return "\n".join(md)


async def _sample_workspace_feedback(workspace_id: str, limit: int = 3000) -> List[Dict[str, Any]]:
    """A bounded sample of workspace feedback used to ground generated documents."""
    if database._mongodb_available:
        records = await db.feedback.find({"workspace_id": workspace_id}).limit(limit).to_list(length=limit)
    else:
        records = (await fallback_db.find_all_feedback_by_workspace(workspace_id))[:limit]
    for record in records:
        if "_id" in record:
            record["_id"] = str(record["_id"])
    return records


async def build_document_evidence(
    workspace_id: str,
    cached_insights: Optional[Dict[str, Any]],
    subject: str,
    source_details: Dict[str, Any],
    sample_quotes: List[str],
    generation_method: str,
) -> Dict[str, Any]:
    """
    Measure the evidence behind a generated document: real counts, ratings and vocabulary.

    Shared by the PRD and user-story services so both ground on the same measured facts.

    Nothing here is estimated. Every value is computed from feedback stored in the
    workspace, so a generated document can state its own provenance.
    """
    insights = cached_insights or {}
    records = await _sample_workspace_feedback(workspace_id)

    source_terms = [str(term) for term in (source_details.get("keywords") or []) if str(term).strip()]
    subject_terms = content_tokens(subject)[:8]
    scoped = match_records_by_terms(records, source_terms or subject_terms)
    if not scoped and sample_quotes:
        quote_text = " ".join(sample_quotes[:3])
        scoped = match_records_by_terms(records, content_tokens(quote_text)[:8])
    if not scoped:
        scoped = records

    stats = rating_stats(scoped)
    negative_count = sum(1 for record in scoped if _resolve_sentiment(record) == "negative")

    # When the source already published its own totals (the insights analysis counts them
    # across the whole workspace), the document must cite those numbers: a PRD opened from
    # "Pay Premium (615 records, avg 1.3)" cannot report a different count for the same
    # subject, which is what re-matching a bounded sample would produce.
    reported_count = source_details.get("affected_users_count") or source_details.get("request_count")
    score_breakdown = source_details.get("score_breakdown") or {}
    reported_avg_rating = score_breakdown.get("avg_rating")
    reported_negative_pct = score_breakdown.get("negative_sentiment_pct")
    if reported_count:
        stats["count"] = int(reported_count)
    if reported_avg_rating is not None:
        stats["avg_rating"] = reported_avg_rating
    if reported_negative_pct is not None and reported_count:
        negative_count = round(float(reported_negative_pct) * int(reported_count) / 100)

    asking_records = [
        record for record in scoped
        if any(marker in f"{record.get('title') or ''} {record.get('content') or ''}".lower()
               for marker in REQUEST_MARKERS)
    ]

    other_clusters = [
        str(cluster.get("cluster_name"))
        for cluster in (insights.get("feature_clusters") or [])
        if cluster.get("cluster_name") and str(cluster.get("cluster_name")) != subject
    ]

    # The source's own keywords name the topic; the mined phrases describe how users
    # talk about it. Keywords lead so a scoped subset cannot lose its own subject.
    terms: List[str] = []
    for term in list(source_terms) + top_phrases(scoped, limit=6):
        if term and term not in terms:
            terms.append(term)

    return {
        "generation_method": generation_method,
        "workspace_name": insights.get("workspace_name"),
        "total_analyzed": int(insights.get("total_analyzed") or len(records)),
        "records": scoped,
        "top_terms": terms[:6],
        "request_terms": request_phrases(scoped, limit=4),
        "stats": stats,
        "negative_count": negative_count,
        "request_count": len(asking_records),
        "other_clusters": other_clusters[:4],
        "pain_point_titles": [str(p.get("title")) for p in (insights.get("pain_points") or []) if p.get("title")][:6],
    }


def _generate_fallback_prd(
    title: str,
    subject: str,
    source_type: str,
    source_details: Dict[str, Any],
    sample_quotes: List[str],
    evidence: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Build a document from measured workspace evidence when no AI provider is reachable.

    Every figure below is computed from this workspace's feedback. Where a PRD normally
    asserts a target, persona or infrastructure SLA, this engine states the measured
    baseline and labels the target as a proposal — inventing adoption numbers, personas
    or architecture would misrepresent the customer evidence the document exists to show.
    """
    evidence = evidence or {}
    stats = evidence.get("stats") or {}
    terms = [str(term) for term in (evidence.get("top_terms") or source_details.get("keywords") or []) if str(term).strip()][:6]
    if not terms:
        terms = [subject]
    term_text = ", ".join(terms[:4])

    count = int(
        stats.get("count")
        or source_details.get("request_count")
        or source_details.get("affected_users_count")
        or len(sample_quotes)
        or 0
    )
    total_analyzed = int(evidence.get("total_analyzed") or count)
    avg_rating = stats.get("avg_rating")
    avg_text = f"{avg_rating}/5.0" if avg_rating is not None else "not rated"
    low_rating_count = int(stats.get("low_rating_count") or 0)
    negative_count = int(evidence.get("negative_count") or 0)
    request_count = int(evidence.get("request_count") or 0)
    negative_pct = round(negative_count / count * 100, 1) if count else 0.0
    request_terms = [str(term) for term in (evidence.get("request_terms") or []) if str(term).strip()] or terms
    other_areas = [str(name) for name in (evidence.get("other_clusters") or []) if str(name).strip()]
    matched_records = evidence.get("records") or []
    term_counts = {term: len(match_records_by_terms(matched_records, [term])) for term in terms[:4]}

    personas = []
    if request_count:
        personas.append({
            "role": "Users asking for a change",
            "description": f"{request_count} of the {count} records matched for this topic ask for something (e.g. {', '.join(request_terms[:3])}).",
            "pain_points": terms[:2],
            "goals": request_terms[:3],
        })
    if negative_count:
        personas.append({
            "role": "Users reporting problems",
            "description": f"{negative_count} of the {count} matched records are negative (average rating {avg_text}).",
            "pain_points": terms[:3],
            "goals": [],
        })
    if not personas:
        personas.append({
            "role": "Users discussing this topic",
            "description": f"{count} feedback records in this workspace mention {term_text}.",
            "pain_points": terms[:3],
            "goals": [],
        })

    bug_count = sum(
        1 for record in matched_records
        if _resolve_category(record) in ("bug_report", "performance_issue")
    )
    non_functional = [
        {
            "category": "Evidence",
            "requirement": (
                f"This document is grounded in {count} of {total_analyzed} records in the workspace; "
                "re-running the workspace analysis must confirm any change it reports."
            ),
        },
    ]
    if bug_count:
        non_functional.append({
            "category": "Reliability",
            "requirement": f"Clear the {bug_count} bug or performance reports mentioning {term_text}.",
        })
    non_functional.append({
        "category": "Traceability",
        "requirement": "Each requirement maps to a measured feedback count listed under Evidence & Method.",
    })

    # Dependencies and infrastructure are intentionally not asserted: this engine has no
    # visibility into the product's stack, and inventing SLAs would misrepresent the evidence.
    technical_dependencies: List[str] = []

    journeys = []
    for index, record in enumerate(matched_records[:3], start=1):
        rating = record.get("rating")
        journeys.append({
            "step": index,
            "stage": "Reported experience",
            "user_action": (record.get("content") or record.get("title") or "")[:160],
            "system_response": (
                f"Recorded as {_resolve_category(record)} with {_resolve_sentiment(record)} sentiment"
                + (f", rating {rating}/5" if rating is not None else "")
            ),
        })

    requirements = []
    for index, term in enumerate(terms[:3], start=1):
        term_records = match_records_by_terms(matched_records, [term])
        term_low = sum(1 for record in term_records if (record.get("rating") or 5) <= 2)
        requirements.append({
            "id": f"FR-{index:02d}",
            "title": titleize(term),
            "description": f"Address the {len(term_records)} feedback records in this workspace that mention {term}.",
            "priority": "P0" if index == 1 else "P1",
            "acceptance_criteria": [
                f"Reports mentioning {term} with a rating of 2 or lower fall below the current {term_low}.",
                f"A re-analysis of this workspace shows no new negative report mentioning {term}.",
            ],
            "edge_cases": [],
        })

    if len(requirements) < 2:
        # One requirement reads as an incomplete document. This structural requirement is
        # still checkable against the workspace, unlike an invented metric would be.
        requirements.append({
            "id": f"FR-{len(requirements) + 1:02d}",
            "title": f"{subject}: failure and recovery path",
            "description": f"Define what a user sees when the {subject} flow fails and how they recover.",
            "priority": "P1",
            "acceptance_criteria": [
                f"No new negative report mentioning {term_text} appears in the next workspace analysis cycle.",
                "Recovery is verified against workspace feedback rather than assumed.",
            ],
            "edge_cases": [],
        })

    success_metrics = [
        {
            "metric": f"Negative reports mentioning {term_text}",
            "baseline": f"{negative_count} of {count} matched records ({negative_pct}%)",
            "target": "Proposed: halve the negative share",
            "tracking_mechanism": "Re-run this workspace analysis",
        },
        {
            "metric": f"Average rating of records mentioning {term_text}",
            "baseline": avg_text,
            "target": "Proposed: +0.5 on the measured baseline",
            "tracking_mechanism": "Re-run this workspace analysis",
        },
    ]

    risks = [
        {
            "risk": f"Only {count} of {total_analyzed} analysed records mention this topic; users who never leave feedback are not represented.",
            "severity": "medium",
            "mitigation": "Treat every figure here as a measured lower bound and re-check after release.",
        },
        {
            "risk": "Reports may repeat the same underlying event, and this workspace carries no per-user identity, so reach cannot be counted.",
            "severity": "low",
            "mitigation": "Compare against support or telemetry volume before committing scope.",
        },
    ]

    clean_title = title or f"PRD: {subject}"

    return {
        "title": clean_title,
        "evidence": {
            "generated_by": evidence.get("generation_method") or "deterministic engine",
            "workspace": evidence.get("workspace_name"),
            "records_analyzed": total_analyzed,
            "records_supporting_this_document": count,
            "terms": terms,
            "avg_rating": avg_rating,
            "negative_reports": negative_count,
            "method": (
                "Every figure in this document is computed from feedback stored in this workspace. "
                "Targets are proposals derived from the measured baseline, not measurements."
            ),
        },
        "executive_summary": (
            f"{count} of the {total_analyzed} analysed feedback records in this workspace mention {term_text} "
            f"(average rating {avg_text}; {negative_count} negative, {negative_pct}% of the matched records). "
            f"This document scopes that demand using the evidence in the workspace: the quotes, counts and "
            f"ratings behind every section are listed under Evidence & Method."
        ),
        "problem_statement": (
            f"Customers mention {term_text} in {count} records. "
            + (
                f"Typical reports: {('; '.join(sample_quotes[:2]))}. "
                if sample_quotes else
                "No verbatim quotes were stored for this topic. "
            )
            + f"{low_rating_count} of the rated records give 1 or 2 stars, which is why this topic ranks where it does."
        ),
        "target_users_and_personas": personas,
        "goals_and_objectives": [
            f"Measured baseline: {count} of {total_analyzed} analysed records mention {term_text} ({negative_pct}% negative, average rating {avg_text}).",
            f"Proposed target: halve the negative share for this topic, currently {negative_count} records.",
            (
                f"Measured baseline: {low_rating_count} of these records carry a rating of 2 or lower."
                if low_rating_count else
                f"Ratings are unavailable for most records mentioning {term_text}, so rating baselines are not claimed."
            ),
        ],
        "scope_in": (
            [f"{titleize(term)} — {term_counts.get(term, 0)} reports in this workspace" for term in terms[:3]]
            or [f"The {count} records mentioning {term_text}"]
        ),
        "scope_out": (
            [f"Other demand areas stay out of scope: {name}" for name in other_areas]
            or ["No other demand areas are recorded in this workspace's current analysis."]
        ),
        "user_journeys": journeys,
        "functional_requirements": requirements,
        "non_functional_requirements": non_functional,
        "success_metrics_kpis": success_metrics,
        "technical_dependencies": technical_dependencies,
        "risks_and_mitigations": risks,
    }


async def generate_prd_with_ai(
    workspace_id: str,
    title: Optional[str] = None,
    feature_cluster_id: Optional[str] = None,
    pain_point_id: Optional[str] = None,
    custom_prompt: Optional[str] = None,
    target_audience: Optional[str] = None,
    strategic_goals: Optional[str] = None,
    tone: str = "comprehensive",
) -> Dict[str, Any]:
    """
    Generate a complete, enterprise-grade PRD using Google Gemini (Pure AI)
    with Groq fallback and deterministic fallback engine.
    Grounded 100% in workspace feedback and customer evidence.
    """
    # 1. Gather context from workspace
    source_type = "custom"
    source_id = None
    subject = title or custom_prompt or "Core Product Improvement"
    source_details: Dict[str, Any] = {}
    sample_quotes: List[str] = []

    # Check insights for feature cluster or pain point
    cached_insights = None
    if database._mongodb_available:
        cached_insights = await db.workspace_insights.find_one({"workspace_id": workspace_id})
    else:
        cached_insights = await fallback_db.get_workspace_insights(workspace_id)

    if feature_cluster_id and cached_insights:
        for c in cached_insights.get("feature_clusters", []):
            if c.get("id") == feature_cluster_id:
                source_type = "feature_cluster"
                source_id = feature_cluster_id
                subject = c.get("cluster_name", subject)
                source_details = c
                sample_quotes = c.get("sample_requests", []) or c.get("distinct_sample_quotes", [])
                break

    elif pain_point_id and cached_insights:
        for pp in cached_insights.get("pain_points", []):
            if pp.get("id") == pain_point_id:
                source_type = "pain_point"
                source_id = pain_point_id
                subject = pp.get("title", subject)
                source_details = pp
                sample_quotes = pp.get("sample_quotes", []) or pp.get("distinct_sample_quotes", [])
                break

    # If quotes are still empty, fetch top negative or feature quotes from feedback
    if not sample_quotes:
        if database._mongodb_available:
            cursor = db.feedback.find({"workspace_id": workspace_id}).limit(15)
            fbs = await cursor.to_list(length=15)
        else:
            fbs = await fallback_db.find_all_feedback_by_workspace(workspace_id)
            fbs = fbs[:15]
        sample_quotes = [f.get("content", "") for f in fbs if f.get("content")]

    clean_quotes = "\n".join([f"- \"{q[:150]}\"" for q in sample_quotes[:10]])
    evidence = await build_document_evidence(
        workspace_id,
        cached_insights,
        subject,
        source_details,
        sample_quotes,
        generation_method="AI provider",
    )

    prompt = f"""You are a Principal Product Manager and Enterprise Technical Architect at a tier-1 software company.
Write an authentic, comprehensive Product Requirement Document (PRD) for:
Focus / Subject: {subject}
Custom Specifications: {custom_prompt or 'None'}
Target Audience: {target_audience or 'Not specified'}
Strategic Goals: {strategic_goals or 'Not specified'}
Tone: {tone}

Measured evidence from this workspace (computed, do not contradict it):
- Records analysed: {evidence.get('total_analyzed')}
- Records matching this subject: {(evidence.get('stats') or {}).get('count')}
- Average rating of those records: {(evidence.get('stats') or {}).get('avg_rating')}
- Negative records among them: {evidence.get('negative_count')}
- Phrases users actually wrote: {', '.join(evidence.get('top_terms') or [])}

Real Customer Feedback & Quotes from Workspace:
{clean_quotes if clean_quotes else 'No verbatim quotes were retrieved for this subject.'}

Return ONLY a valid JSON object matching this exact schema:
{{
  "title": "Clear PRD Title",
  "executive_summary": "Thorough executive briefing (2 paragraphs) summarizing the initiative, strategic importance, and expected business outcome.",
  "problem_statement": "Deep root-cause customer problem statement grounded in the provided customer feedback quotes.",
  "target_users_and_personas": [
    {{
      "role": "Persona Role Name",
      "description": "Background and behavior archetype",
      "pain_points": ["Pain point 1", "Pain point 2"],
      "goals": ["Goal 1", "Goal 2"]
    }}
  ],
  "goals_and_objectives": [
    "Quantitative objective 1 with specific target metric",
    "Quantitative objective 2 with specific target metric"
  ],
  "scope_in": ["Key MVP capability 1", "Key MVP capability 2", "Key MVP capability 3"],
  "scope_out": ["Deferred capability 1", "Deferred capability 2"],
  "user_journeys": [
    {{
      "step": 1,
      "stage": "Discovery / Trigger",
      "user_action": "What the user attempts or clicks",
      "system_response": "What the application responds and displays"
    }},
    {{
      "step": 2,
      "stage": "Execution / Interaction",
      "user_action": "User inputs data or performs core action",
      "system_response": "System verifies, processes asynchronously and displays immediate feedback"
    }}
  ],
  "functional_requirements": [
    {{
      "id": "FR-01",
      "title": "Core Requirement Name",
      "description": "Exhaustive technical and behavioral specification",
      "priority": "P0",
      "acceptance_criteria": [
        "Given X when Y then Z",
        "Criterion 2"
      ],
      "edge_cases": ["Edge case 1", "Edge case 2"]
    }},
    {{
      "id": "FR-02",
      "title": "Secondary Requirement Name",
      "description": "Exhaustive specification",
      "priority": "P1",
      "acceptance_criteria": ["Criterion 1", "Criterion 2"],
      "edge_cases": ["Edge case 1"]
    }}
  ],
  "non_functional_requirements": [
    {{"category": "Performance", "requirement": "P95 latency SLA"}},
    {{"category": "Security", "requirement": "Compliance and encryption standards"}},
    {{"category": "Scalability", "requirement": "Throughput and concurrency targets"}},
    {{"category": "Accessibility", "requirement": "WCAG 2.1 AA specifications"}}
  ],
  "success_metrics_kpis": [
    {{"metric": "Primary metric grounded in the feedback", "baseline": "Measured: <value from the evidence above>", "target": "Proposed: <target outcome>", "tracking_mechanism": "How this will actually be tracked"}},
    {{"metric": "Second metric", "baseline": "Measured: <value> or Not measured", "target": "Proposed: <target outcome>", "tracking_mechanism": "How this will actually be tracked"}}
  ],
  "technical_dependencies": [
    "API endpoint requirements",
    "Database schema updates or indexing",
    "Worker queue or third party services"
  ],
  "risks_and_mitigations": [
    {{"risk": "Specific technical or user adoption risk", "severity": "medium", "mitigation": "Actionable engineering or operational mitigation plan"}}
  ]
}}

Ensure:
- All functional requirements have IDs (FR-01, FR-02, FR-03, etc.).
- Priorities must be 'P0', 'P1', or 'P2'.
- Ground all problem statements in actual customer evidence.
- Never invent metrics, personas, technologies or SLAs that the evidence above does not support.
- Every 'baseline' must start with 'Measured:' using a value from the evidence above, or be exactly 'Not measured'. Never state telemetry baselines (conversion, retention, latency, uptime) this workspace cannot observe.
- Every 'target' must start with 'Proposed:'.
- Non-functional requirements are proposed engineering targets: phrase them as proposals rather than asserting infrastructure numbers as measured facts.
- Return ONLY valid JSON, no markdown formatting around the JSON.
"""

    parsed_result = None
    ai_model_used = None

    # 1. Attempt Google Gemini Pure AI
    gem_client = get_gemini_client()
    if gem_client:
        for g_model in GEMINI_MODELS:
            try:
                from google.genai import types
                logger.info(f"Generating PRD with Google Gemini model {g_model}...")
                response = gem_client.models.generate_content(
                    model=g_model,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        temperature=0.25,
                    ),
                )
                parsed = _extract_json_from_text(response.text)
                if parsed and "functional_requirements" in parsed and "problem_statement" in parsed:
                    parsed_result = parsed
                    ai_model_used = f"Google Gemini ({g_model})"
                    logger.info("PRD generated successfully with Google Gemini!")
                    break
            except Exception as e:
                logger.warning(f"Gemini PRD generation error on {g_model}: {e}. Retrying next...")

    # 2. Attempt Mistral AI Fallback (free Experiment tier, OpenAI-compatible)
    if not parsed_result:
        mistral_client = get_mistral_client()
        if mistral_client:
            for m_name in MISTRAL_MODELS:
                try:
                    logger.info(f"Attempting Mistral PRD generation using {m_name}...")
                    response = mistral_client.chat.completions.create(
                        model=m_name,
                        messages=[
                            {"role": "system", "content": "You are a Principal Product Manager. Respond ONLY in valid JSON."},
                            {"role": "user", "content": prompt},
                        ],
                        temperature=0.2,
                        max_tokens=3200,
                        response_format={"type": "json_object"},
                    )
                    content = response.choices[0].message.content
                    parsed = _extract_json_from_text(content)
                    if parsed and "functional_requirements" in parsed:
                        parsed_result = parsed
                        ai_model_used = f"Mistral ({m_name})"
                        logger.info("PRD generated successfully with Mistral AI fallback!")
                        break
                except Exception as e:
                    logger.warning(f"Mistral PRD generation error on {m_name}: {e}...")

    # 3. Attempt Groq AI Fallback
    if not parsed_result:
        groq_client = get_groq_client()
        if groq_client:
            for m_name in GROQ_MODELS:
                try:
                    logger.info(f"Attempting Groq PRD generation using {m_name}...")
                    response = groq_client.chat.completions.create(
                        model=m_name,
                        messages=[
                            {"role": "system", "content": "You are a Principal Product Manager. Respond ONLY in valid JSON."},
                            {"role": "user", "content": prompt},
                        ],
                        temperature=0.2,
                        max_tokens=3200,
                        response_format={"type": "json_object"} if m_name in ["openai/gpt-oss-20b", "openai/gpt-oss-120b", "qwen/qwen3.8-27b"] else None
                    )
                    content = response.choices[0].message.content
                    parsed = _extract_json_from_text(content)
                    if parsed and "functional_requirements" in parsed:
                        parsed_result = parsed
                        ai_model_used = f"Groq ({m_name})"
                        logger.info("PRD generated successfully with Groq AI fallback!")
                        break
                except Exception as e:
                    logger.warning(f"Groq PRD generation error on {m_name}: {e}...")

    if parsed_result:
        evidence["generation_method"] = ai_model_used or "AI provider"

    # 3. Evidence-based fallback if no AI provider is reachable
    if not parsed_result:
        logger.info("Generating PRD from measured workspace evidence...")
        evidence["generation_method"] = "deterministic evidence engine (no AI provider reachable)"
        parsed_result = _generate_fallback_prd(
            title=title or f"PRD: {subject}",
            subject=subject,
            source_type=source_type,
            source_details=source_details,
            sample_quotes=sample_quotes,
            evidence=evidence,
        )

    # 4. Guarantee an actionable minimum when a model returns a valid but thin
    #    document (e.g. the stories/requirements list is truncated).
    requirements = parsed_result.get("functional_requirements") or []
    if len(requirements) < 3:
        logger.info("AI PRD returned fewer than 3 functional requirements; topping up from workspace evidence.")
        filler = _generate_fallback_prd(
            title=title or f"PRD: {subject}",
            subject=subject,
            source_type=source_type,
            source_details=source_details,
            sample_quotes=sample_quotes,
            evidence=evidence,
        )
        merged = [dict(fr) for fr in requirements if isinstance(fr, dict)]
        merged.extend(dict(fr) for fr in filler.get("functional_requirements", [])[: 3 - len(merged)])
        # Renumber sequentially so appended IDs cannot collide with the model's.
        for index, fr in enumerate(merged, start=1):
            fr["id"] = f"FR-{index:02d}"
        parsed_result["functional_requirements"] = merged

    # Provenance block: attached to every document, AI-written or not, so a reader can
    # always see which engine produced it and how many records back it up.
    stats = evidence.get("stats") or {}
    evidence_summary = {
        "generated_by": evidence.get("generation_method"),
        "workspace": evidence.get("workspace_name"),
        "records_analyzed": evidence.get("total_analyzed"),
        "records_supporting_this_document": stats.get("count"),
        "avg_rating": stats.get("avg_rating"),
        "negative_reports": evidence.get("negative_count"),
        "terms": evidence.get("top_terms"),
        "method": (
            "Every count, rating and quote in this document is computed from feedback stored in "
            "this workspace. Targets are proposals derived from the measured baseline."
        ),
    }

    # Assemble complete PRD Document
    prd_id = f"prd_{uuid.uuid4().hex[:12]}"
    now = datetime.now(timezone.utc)

    final_prd: Dict[str, Any] = {
        "id": prd_id,
        "workspace_id": workspace_id,
        "title": parsed_result.get("title", title or f"PRD: {subject}"),
        "status": "draft",
        "version": "1.0",
        "source_type": source_type,
        "source_id": source_id,
        "executive_summary": parsed_result.get("executive_summary", ""),
        "problem_statement": parsed_result.get("problem_statement", ""),
        "target_users_and_personas": parsed_result.get("target_users_and_personas", []),
        "goals_and_objectives": parsed_result.get("goals_and_objectives", []),
        "scope_in": parsed_result.get("scope_in", []),
        "scope_out": parsed_result.get("scope_out", []),
        "user_journeys": parsed_result.get("user_journeys", []),
        "functional_requirements": parsed_result.get("functional_requirements", []),
        "non_functional_requirements": parsed_result.get("non_functional_requirements", []),
        "success_metrics_kpis": parsed_result.get("success_metrics_kpis", []),
        "technical_dependencies": parsed_result.get("technical_dependencies", []),
        "risks_and_mitigations": parsed_result.get("risks_and_mitigations", []),
        "ai_generated": bool(ai_model_used),
        "ai_model": ai_model_used or "Deterministic evidence engine",
        "evidence": evidence_summary,
        "created_at": now.isoformat(),
        "updated_at": now.isoformat(),
    }

    final_prd["raw_markdown"] = _build_markdown_from_prd(final_prd)

    # Persist in Database
    if database._mongodb_available:
        await db.prds.insert_one(dict(final_prd))
    else:
        await fallback_db.save_prd(dict(final_prd))

    return final_prd


async def get_prds_for_workspace(workspace_id: str) -> List[Dict[str, Any]]:
    """Retrieve all PRDs belonging to a workspace."""
    if database._mongodb_available:
        cursor = db.prds.find({"workspace_id": workspace_id}).sort("created_at", -1)
        records = await cursor.to_list(length=None)
        for r in records:
            if "_id" in r:
                r["_id"] = str(r["_id"])
        return records
    else:
        return await fallback_db.find_prds_by_workspace(workspace_id)


async def get_prd_by_id(prd_id: str) -> Optional[Dict[str, Any]]:
    """Fetch single PRD by ID."""
    if database._mongodb_available:
        prd = await db.prds.find_one({"id": prd_id})
        if prd and "_id" in prd:
            prd["_id"] = str(prd["_id"])
        return prd
    else:
        return await fallback_db.find_prd_by_id(prd_id)


async def update_prd(prd_id: str, updates: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """Update existing PRD details."""
    updates["updated_at"] = datetime.now(timezone.utc).isoformat()
    
    # If content changed, rebuild markdown
    existing = await get_prd_by_id(prd_id)
    if not existing:
        return None
        
    merged = {**existing, **updates}
    if "raw_markdown" not in updates:
        updates["raw_markdown"] = _build_markdown_from_prd(merged)

    if database._mongodb_available:
        await db.prds.update_one({"id": prd_id}, {"$set": updates})
        return await get_prd_by_id(prd_id)
    else:
        return await fallback_db.update_prd(prd_id, updates)


async def delete_prd(prd_id: str) -> bool:
    """Delete a PRD."""
    if database._mongodb_available:
        result = await db.prds.delete_one({"id": prd_id})
        return result.deleted_count > 0
    else:
        return await fallback_db.delete_prd(prd_id)
