"""
Conversational Product Intelligence Assistant (PM Copilot) data models.
Milestone 3: Grounded multi-turn conversational AI for workspace feedback queries,
PRD ideation, story decomposition, and prioritization questions.
"""

from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class SourceCitation(BaseModel):
    """Specific feedback or analytical source cited by the copilot."""
    type: str = Field(..., description="'pain_point', 'feature_cluster', 'theme', or 'feedback_quote'")
    title: str = Field(..., description="Title or excerpt of the source")
    detail: Optional[str] = Field(None, description="Detailed quote, volume count, or metric")
    id: Optional[str] = Field(None, description="Database record ID if applicable")


class CopilotAction(BaseModel):
    """Recommended interactive shortcut generated by the copilot."""
    action_type: str = Field(..., description="'create_prd', 'generate_stories', 'prioritize_feature', 'view_feedback'")
    label: str = Field(..., description="Button label, e.g. 'Generate PRD for this'")
    payload: Dict[str, Any] = Field(default_factory=dict, description="Payload to pre-populate generation wizards")


class CopilotChatRequest(BaseModel):
    """Chat message sent by the user to the PM Copilot."""
    workspace_id: str = Field(..., description="Workspace ID providing context")
    message: str = Field(..., description="User query or command")
    session_id: Optional[str] = Field("default", description="Conversation session ID")
    conversation_history: Optional[List[Dict[str, str]]] = Field(default_factory=list, description="Recent conversation turns")


class CopilotChatResponse(BaseModel):
    """Rich conversational response returned by PM Copilot."""
    reply: str = Field(..., description="Markdown formatted response")
    session_id: str = Field(..., description="Conversation session ID")
    sources_cited: List[SourceCitation] = Field(default_factory=list, description="Feedback items and insights cited")
    suggested_followups: List[str] = Field(default_factory=list, description="Relevant quick prompt suggestions")
    action_suggested: Optional[CopilotAction] = Field(None, description="Suggested action button")
    context_summary: Dict[str, Any] = Field(default_factory=dict, description="Summary of context loaded into Copilot")
    ai_model: str = Field("Google Gemini 3.6 Flash", description="AI model used")
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class StoredChatMessage(BaseModel):
    """Persistent chat message in database."""
    id: str = Field(..., description="Message ID")
    workspace_id: str
    session_id: str
    sender: str  # 'user' | 'assistant'
    content: str
    sources_cited: List[Dict[str, Any]] = Field(default_factory=list)
    suggested_followups: List[str] = Field(default_factory=list)
    action_suggested: Optional[Dict[str, Any]] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
