"""
User Story and Acceptance Criteria data models for Milestone 3.
Defines schemas for automated Agile user stories with Gherkin acceptance criteria,
story sizing (Fibonacci/T-Shirt), priority, and Kanban status tracking.
"""

from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


class AcceptanceCriterion(BaseModel):
    """Gherkin-style Acceptance Criteria entry."""
    scenario: str = Field(..., description="Scenario title, e.g. 'Successful appeal upload'")
    given: str = Field(..., description="Preconditions (Given...)")
    when: str = Field(..., description="User action or event (When...)")
    then: str = Field(..., description="Expected system outcome (Then...)")


class UserStoryModel(BaseModel):
    """Structured Agile User Story with acceptance criteria and estimation."""
    id: str = Field(..., description="Unique User Story ID (e.g. 'US-101')")
    workspace_id: str = Field(..., description="Workspace ID")
    prd_id: Optional[str] = Field(None, description="Linked PRD ID if generated from a PRD")
    feature_cluster_id: Optional[str] = Field(None, description="Linked Feature Cluster ID")
    title: str = Field(..., description="Short story headline")
    role: str = Field(..., description="Persona/role: 'As a <role>'")
    action: str = Field(..., description="Desired capability: 'I want to <action>'")
    benefit: str = Field(..., description="Business/user outcome: 'So that <benefit>'")
    full_statement: str = Field(..., description="Complete user story statement")
    acceptance_criteria: List[AcceptanceCriterion] = Field(default_factory=list)
    story_points: int = Field(3, description="Fibonacci estimation: 1, 2, 3, 5, 8, 13")
    t_shirt_size: str = Field("M", description="XS, S, M, L, XL")
    priority: str = Field("medium", description="high, medium, low")
    status: str = Field("backlog", description="backlog, in_progress, in_review, done")
    definition_of_done: List[str] = Field(default_factory=list, description="Quality checklist items")
    technical_notes: Optional[str] = Field(None, description="API endpoints, DB schema, or security notes")
    ai_generated: bool = Field(True, description="Whether generated by Generative AI")
    ai_model: Optional[str] = Field(None, description="AI model that produced the story, if any")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class UserStoryGenerateRequest(BaseModel):
    """Request payload for generating user stories with AI."""
    workspace_id: str = Field(..., description="Workspace ID")
    prd_id: Optional[str] = Field(None, description="Generate stories from this PRD")
    feature_cluster_id: Optional[str] = Field(None, description="Generate stories from this feature cluster")
    custom_prompt: Optional[str] = Field(None, description="Custom requirement or story description")
    count: Optional[int] = Field(5, description="Number of stories to generate (1 to 10)")
    persona: Optional[str] = Field(None, description="Target persona or user role")


class UserStoryUpdateRequest(BaseModel):
    """Payload for updating user story details."""
    title: Optional[str] = None
    role: Optional[str] = None
    action: Optional[str] = None
    benefit: Optional[str] = None
    full_statement: Optional[str] = None
    acceptance_criteria: Optional[List[Dict[str, Any]]] = None
    story_points: Optional[int] = None
    t_shirt_size: Optional[str] = None
    priority: Optional[str] = None
    status: Optional[str] = None
    definition_of_done: Optional[List[str]] = None
    technical_notes: Optional[str] = None


class UserStoryStatusUpdateRequest(BaseModel):
    """Payload for updating just the status (e.g. dragging across Kanban)."""
    status: str = Field(..., description="backlog, in_progress, in_review, done")
